global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'pandasobhan22@gmail.com'
  smtp_auth_username: 'pandasobhan22@gmail.com'
  smtp_auth_identity: 'pandasobhan22@gmail.com'
  smtp_auth_password: 'wplj rcbz wuiz mxkm'   # the app password, not real password
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'email-alerts'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'pandasobhan22@gmail.com'
        send_resolved: true
