global:
  scrape_interval: 4s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crypto-analytics'
    static_configs:
      - targets: ['host.docker.internal:3030']

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
